from typing import Any, Dict
from pydantic import BaseModel

# Mock Planner Response
MOCK_ARCHITECTURE = {
    "files": [
        {
            "filepath": "calculator.py",
            "description": "Core calculator logic with add and subtract functions."
        },
        {
            "filepath": "utils.py",
            "description": "Utility formatting and helper functions for outputs."
        }
    ],
    "explanation": "A clean, modular calculator implementation splitting calculation logic from presentation formatting."
}

# Mock Coder Code Contents
MOCK_BUGGY_CALCULATOR = """
def add(a, b):
    # Intentional bug for debugging test cycle: returns wrong sum
    return a + b + 99

def subtract(a, b):
    return a - b
"""

MOCK_CORRECT_CALCULATOR = """
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b
"""

MOCK_UTILS = """
def format_result(value: int) -> str:
    return f"Result: {value}"
"""

# Mock Test Writer Code Content
MOCK_TESTS = """
import pytest
from calculator import add, subtract
from utils import format_result

def test_add():
    assert add(2, 3) == 5

def test_subtract():
    assert subtract(5, 3) == 2

def test_format():
    assert format_result(5) == "Result: 5"
"""

# Mock Review Notes
MOCK_REVIEW_NOTES = [
    {
        "severity": "suggestion",
        "file": "calculator.py",
        "note": "Code structure is clean, and imports match architectural blueprint."
    }
]

# Mock README
MOCK_README = """
# Sandboxed Calculator Project

A multi-file modular Python calculator project generated by the Multi-Agent Coding Assistant.

## Modules

*   `calculator.py`: Holds basic mathematical functions (`add`, `subtract`).
*   `utils.py`: Holds output formatting helpers (`format_result`).

## Usage

```python
from calculator import add
from utils import format_result

val = add(2, 3)
print(format_result(val))  # Result: 5
```

## Running Tests

Tests are written using `pytest`. Run them inside your environment:

```bash
pytest
```
"""

def get_mock_supervisor_decision(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Decides the next agent based on the current state in Mock LLM Mode.
    Supports looping and failing when the debugger repeatedly fails to fix a bug.
    """
    files = state.get("files", {})
    test_files = state.get("test_files", {})
    test_results = state.get("test_results", {})
    lint_results = state.get("lint_results", {})
    iteration_count = state.get("iteration_count", {})
    run_log = state.get("run_log", [])
    
    # Get last acting agent from the run log
    last_agent = run_log[-1].get("agent") if run_log else None
    has_calc_runs_count = iteration_count.get("calculator.py", 0)
    
    # 1. Plan
    if not state.get("architecture") or not state["architecture"].get("files"):
        return {
            "next_agent": "planner",
            "reasoning": "[MOCK] No architecture plan found. Routing to planner."
        }
        
    # 2. Code calculator.py
    if "calculator.py" not in files:
        return {
            "next_agent": "coder",
            "reasoning": "[MOCK] calculator.py has not been written. Routing to coder."
        }
        
    # 3. Code utils.py
    if "utils.py" not in files:
        return {
            "next_agent": "coder",
            "reasoning": "[MOCK] utils.py has not been written. Routing to coder."
        }
        
    # 4. Write tests
    if "test_calculator.py" not in test_files:
        return {
            "next_agent": "test_writer",
            "reasoning": "[MOCK] test_calculator.py not written. Routing to test_writer."
        }
        
    # 5. Run tests (first run or rerun after debugger / coder changes code)
    # If the last node was coder or debugger, we must run tests to see results.
    if last_agent in ["coder", "debugger"] or not test_results:
        return {
            "next_agent": "executor",
            "reasoning": f"[MOCK] Code updated by {last_agent}. Routing to executor to run tests."
        }
        
    # 6. Check if tests failed
    failed_tests = any("FAILED" in str(res) for res in test_results.values())
    if failed_tests:
        if has_calc_runs_count < 3:
            return {
                "next_agent": "debugger",
                "reasoning": f"[MOCK] Tests failed on revision {has_calc_runs_count}. Routing to debugger for targeted fix."
            }
        else:
            return {
                "next_agent": "failed",
                "reasoning": f"[MOCK] Tests failed on revision {has_calc_runs_count}. Exceeded debugger retry limit (3). Routing to failed."
            }
        
    # 7. Static analysis
    if not lint_results:
        return {
            "next_agent": "static_analyzer",
            "reasoning": "[MOCK] Tests passed. Routing to static_analyzer for lint checks."
        }
        
    # 8. Reviewer
    if not state.get("review_notes"):
        return {
            "next_agent": "reviewer",
            "reasoning": "[MOCK] Lint check finished. Routing to reviewer to evaluate quality."
        }
        
    # 9. Docs Agent
    if "README.md" not in files:
        return {
            "next_agent": "docs_agent",
            "reasoning": "[MOCK] Code approved. Routing to docs_agent to write documentation."
        }
        
    # 10. Done
    return {
        "next_agent": "done",
        "reasoning": "[MOCK] All stages completed successfully. Routing to done."
    }
